{
  "language": "c",
  "os": [
    "linux",
    "osx"
  ],
  "dist": "xenial",
  "sudo": false,
  "cache": {
    "directories": [
      "$HOME/travis-cache"
    ]
  },
  "compiler": [
    "clang",
    "gcc"
  ],
  "addons": {
    "apt": {
      "sources": [
        {
          "name": "ubuntu-toolchain-r-test"
        }
      ],
      "packages": [
        "language-pack-is",
        "git-svn",
        "apache2",
        "gcc-8"
      ]
    }
  },
  "before_install": [
    "ci/install-dependencies.sh"
  ],
  "script": [
    "ci/run-build-and-tests.sh"
  ],
  "after_failure": [
    "ci/print-test-failures.sh"
  ],
  "notifications": {
    "email": [
      {
        "enabled": false
      }
    ]
  },
  "jobs": {
    "include": [
      {
        "env": [
          {
            "jobname": "GETTEXT_POISON"
          }
        ],
        "os": "linux",
        "before_install": []
      },
      {
        "env": [
          {
            "jobname": "Windows"
          }
        ],
        "os": "linux",
        "before_install": [],
        "script": [
          "test \"$TRAVIS_REPO_SLUG\" != \"git/git\" || ci/run-windows-build.sh $TRAVIS_BRANCH $(git rev-parse HEAD)\n"
        ],
        "after_failure": []
      },
      {
        "env": [
          {
            "jobname": "Linux32"
          }
        ],
        "os": "linux",
        "services": [
          "docker"
        ],
        "before_install": [],
        "script": [
          "ci/run-linux32-docker.sh"
        ]
      },
      {
        "env": [
          {
            "jobname": "StaticAnalysis"
          }
        ],
        "os": "linux",
        "addons": {
          "apt": {
            "packages": [
              "coccinelle"
            ]
          }
        },
        "before_install": [],
        "script": [
          "ci/run-static-analysis.sh"
        ],
        "after_failure": []
      },
      {
        "env": [
          {
            "jobname": "Documentation"
          }
        ],
        "os": "linux",
        "addons": {
          "apt": {
            "packages": [
              "asciidoc",
              "xmlto"
            ]
          }
        },
        "before_install": [],
        "script": [
          "ci/test-documentation.sh"
        ],
        "after_failure": []
      }
    ]
  }
}
